services:
  card-dev:
    container_name: card-dev
    build:
      target: development
    image: card:dev
    command: npm run dev
    cpus: 2
    mem_limit: 2048m
    ports:
      - "5000:8080"
    volumes:
      - ./src:/var/task/src
      - ./public:/var/task/public
      - ./styles:/var/task/styles
      - ./nodemon.json:/var/task/nodemon.json:ro
      - ./tsconfig.json:/var/task/tsconfig.json:ro
    environment:
      STYLES_DIR: /var/task/styles
      STYLES_WATCH: "1"
    env_file:
      - .env
  card-prod:
    container_name: card-prod
    build:
      target: production
    env_file:
      - .env
    image: card:prod
    cpus: 2
    mem_limit: 2048m
    ports:
      - "5000:8080"
    volumes:
      - ./styles:/var/task/styles
    environment:
      STYLES_DIR: /var/task/styles
